apiVersion: v1
kind: Service
metadata:
  name: app-postgres-pooler
  namespace: databases
spec:
  selector:
    app: app-postgres-pooler
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
